version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: node:8.11.4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test